name: 'Wait for ECS service deployment to complete.'
description: 'Waits for an ECS service to reach the completed state before continuing.'
branding:
  icon: 'activity'
  color: 'white'
inputs:
  cluster:
    description: 'The ECS cluster the service is in.'
    required: true
  service:
    description: 'The ECS service in the cluster to wait for completed deployment.'
    required: true
  wait-for-minutes:
    description: "Minutes to wait before timing out and failing the action."
    default: 10

runs:
  using: 'node22'
  main: 'dist/index.js'
